import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest'
import { saveJevSettings,deleteJevSettings } from '../../packages/server/src/modules/studio/services/jev/settings'
import { GroupMessageRoutingService,type GroupRoutingDecision } from '../../packages/server/src/modules/studio/services/group-chat/message-routing'
const response={model:'jev',usage:{},answers:{target:{type:'choice',choice:'agent-1',confidence:.98,probabilities:{'agent-1':.98,none:.02}}}}
async function waitFor(check:()=>boolean){for(let i=0;i<100;i++){if(check())return;await new Promise(r=>setTimeout(r,5))}throw new Error('timeout')}
function harness(mode:'off'|'suggest'|'auto'){const decisions:GroupRoutingDecision[]=[];const room:any={id:'room',messageRoutingMode:mode,evaluationProfile:'default',summaryProfile:'default'};const message:any={id:'m1',roomId:'room',senderId:'user',senderName:'Alice',content:'Please analyze logs',timestamp:1,mentions:[]};const storage:any={getRoom:()=>room,getMessage:()=>message,getRoomAgents:()=>[],getMessageRoutingDecision:()=>decisions[0]||null,saveRoutingSuggestion:(d:GroupRoutingDecision)=>{decisions.push(d);return true},claimAndEnqueueAutoRouting:(d:GroupRoutingDecision)=>{const n={...d,status:'queued',queueId:'q1'};decisions.push(n);return n}};return{service:new GroupMessageRoutingService(storage),decisions,message}}
beforeEach(async()=>{vi.stubGlobal('fetch',vi.fn(async()=>Response.json(response)));await saveJevSettings('default',{apiKey:'key',groupMessageRoutingEnabled:true})});afterEach(async()=>{vi.unstubAllGlobals();await deleteJevSettings('default')})
describe('group JEV message routing',()=>{
 it('stores a suggestion without executing it',async()=>{const h=harness('suggest');h.service.schedule(h.message,[{id:'agent-1',name:'Analyst',description:'Analyze logs'}]);await waitFor(()=>h.decisions.length===1);expect(h.decisions[0]).toMatchObject({status:'suggested',targetAgentId:'agent-1'})})
 it('atomically returns queued auto routing through storage',async()=>{const h=harness('auto');h.service.schedule(h.message,[{id:'agent-1',name:'Analyst',description:'Analyze logs'}]);await waitFor(()=>h.decisions.length===1);expect(h.decisions[0]).toMatchObject({status:'queued',queueId:'q1'})})
 it('does not call JEV for off rooms, explicit mentions, or no candidates',async()=>{const fetchMock=vi.mocked(fetch);const h=harness('off');h.service.schedule(h.message,[{id:'agent-1',name:'A',description:''}]);const s=harness('suggest');s.service.schedule({...s.message,mentions:[{type:'agent'}]},[{id:'agent-1',name:'A',description:''}]);s.service.schedule(s.message,[]);await new Promise(r=>setTimeout(r,20));expect(fetchMock).not.toHaveBeenCalled()})
})
